// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `approval/respond` 的参数。
 */
export type ApprovalRespondParams = {
  turnId: string;
  requestId: string;
  approved: boolean;
  /**
   * 记住这个决定：把这条命令本身写进 `<home>/settings.json` 的放行表
   * （不加通配 —— 用户批准的是这条命令，不是这一类）。
   */
  remember: boolean;
};
