// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次「要不要执行」的询问。
 *
 * 服务端把问题抛给客户端后**等待**（默认 120 秒），回答由 `approval/respond`
 * 送来。没人回答、超时、或者根本没有批准通道 —— 一律**按拒绝处理**：默认
 * 拒绝是这个功能的地基，不是它的边界情况。
 */
export type ApprovalRequestedNotification = {
  turnId: string;
  /**
   * 这一轮内的请求号，回答时要原样带回来。
   */
  requestId: string;
  /**
   * 想执行什么（工具名，目前只有 `run_command`）。
   */
  tool: string;
  /**
   * 给人看的动作预览：命令原文，或参数摘要。
   */
  argsPreview: string;
  /**
   * 为什么没被放行规则直接放行。
   */
  reason: string;
  /**
   * 多少毫秒内没人回答就按拒绝算。
   */
  expiresInMs: number;
};
