// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `approval/respond` 的应答。
 */
export type ApprovalRespondResponse = {
  /**
   * 这个请求还在等人回答吗？太晚送达（已超时或那一轮已经结束）时为 false ——
   * 客户端据此知道「我的回答没人听」，而不是以为批准生效了。
   */
  accepted: boolean;
};
