// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigReadParams = {
  /**
   * 只取这几个 key；不给就全量返回。
   */
  keys?: Array<string> | null;
};
