// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingsView } from "./SettingsView";

export type ConfigWriteResponse = {
  /**
   * 写入后的完整配置，便于前端直接替换本地缓存。
   */
  config: SettingsView;
};
