// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConsolidationCompletedNotification = {
  /**
   * 这一批提炼出多少条新 fact；0 表示没到期或没提炼出东西。
   */
  newFacts: number;
};
