// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";
import type { Fact } from "./Fact";
import type { SessionSummary } from "./SessionSummary";
import type { SettingsView } from "./SettingsView";

/**
 * 驾驶舱首屏要的全部东西，一次取齐。
 *
 * 它不是某个 RPC 的应答，而是 `joy dashboard` 那个 HTTP 端点
 * （`GET /api/data`）的载荷。**为什么定义在协议 crate 里**：因为判断标准
 * 只有一条 —— 它跨语言。浏览器那一侧要按它做类型检查，手抄一遍就又会
 * 漂移，而这正是整个工程在消灭的东西。
 *
 * 字段都直接复用协议里的类型：驾驶舱不做二次建模，它就是这些数据的
 * 一个视图。
 */
export type DashboardData = {
  /**
   * ISO 8601，毫秒精度。页面上显示「数据是什么时候的」。
   */
  generatedAt: string;
  config: SettingsView;
  sessions: Array<SessionSummary>;
  facts: Array<Fact>;
  episodes: Array<Episode>;
};
