// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Episode = {
  id: number;
  /**
   * ISO 8601 日期。
   */
  happenedAt: string;
  summary: string;
  createdAt: string | null;
};
