// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Fact = {
  id: number;
  subject: string;
  content: string;
  /**
   * `user`（直接告诉它的）或 `consolidation`（从对话里提炼的）。
   */
  source: string;
  /**
   * 这条事实**关于什么**：`user` / `feedback` / `project` / `reference` /
   * `fact`（兜底）。分类不出来的都落在 `fact`。
   */
  kind: string;
  createdAt: string | null;
};
