// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecision } from "./GateDecision";

export type GateDecidedNotification = {
  turnId: string;
  decision: GateDecision;
};
