// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 检索门的判定：这一轮到底要不要翻记忆。
 * Joy 的 hero moment —— 默认全量检索既慢又会让无关记忆带偏答案。
 */
export type GateDecisionKind = "retrieve" | "skip";
