// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecisionKind } from "./GateDecisionKind";

export type GateDecision = {
  decision: GateDecisionKind;
  /**
   * 门给的理由（≤5 个词的那种）。失败开放时带上原因，便于排查。
   */
  reason: string;
  /**
   * 判定为 retrieve 时的检索词；skip 时为 null。
   */
  query: string | null;
};
