// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 目标循环每判一次就发一条 —— 「为什么又跑了一轮」从来不靠猜。
 */
export type GoalRoundNotification = {
  turnId: string;
  /**
   * 第几轮（从 1 开始）。
   */
  round: number;
  maxRounds: number;
  /**
   * `continuing` / `satisfied` / `impossible` / `round-limit` / `blocked`。
   */
  status: string;
  /**
   * 判断器给的理由（或出口的原因）。
   */
  reason: string;
};
