// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `goal/set` 的参数。`condition` 为空 = 清除目标。
 */
export type GoalSetParams = {
  sessionId: string;
  /**
   * 目标条件（自然语言，比如「让测试全绿」）。空/不传 = 清除。
   */
  condition: string | null;
};
