// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `goal/set` 的应答：设完之后的权威状态。
 */
export type GoalSetResponse = {
  /**
   * 现在有活跃目标吗。
   */
  active: boolean;
  condition: string | null;
  /**
   * 这个目标已经续了几轮。
   */
  roundsUsed: number;
  maxRounds: number;
};
