// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNodeStartedNotification = {
  workflow: string;
  node: string;
  /**
   * 第几次进入该节点（>1 只可能出现在有意设计的环里）。
   */
  visit: number;
};
