// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphEndedNotification = {
  workflow: string;
  ms: number;
  steps: number;
  path: Array<string>;
  error: string | null;
};
