// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphNodeEndedNotification = {
  workflow: string;
  node: string;
  ms: number;
  /**
   * 该节点写回了哪些 state key。
   */
  keys: Array<string>;
  /**
   * 节点抛错时是错误文本；错误只记录、不外抛，整个 run 会正常收尾。
   */
  error: string | null;
};
