// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphRouteKind } from "./GraphRouteKind";

export type GraphInfo = {
  workflow: string;
  route: GraphRouteKind;
  reason: string;
  /**
   * 实际走过的节点名，顺序即执行顺序。
   */
  path: Array<string>;
};
