// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * triage graph 把这一轮判成「快回答」还是「完整走一圈」。
 */
export type GraphRouteKind = "quick" | "full";
