// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";

export type JsonRpcRequest = {
  jsonrpc: string;
  id: RequestId;
  /**
   * 形如 `turn/start`、`<resource>/<method>`，resource 用单数。
   */
  method: string;
  params?: unknown;
};
