// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonRpcError } from "./JsonRpcError";
import type { JsonRpcResponse } from "./JsonRpcResponse";

/**
 * 服务端回的任意一帧：应答或错误。
 */
export type JsonRpcMessage = JsonRpcResponse | JsonRpcError;
