// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "./RequestId";

export type JsonRpcResponse = {
  jsonrpc: string;
  id: RequestId;
  /**
   * 具体结构由 method 决定，解码方按 `*Response` 类型自行 narrow。
   */
  result: unknown;
};
