// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务端主动推送（SSE / stdio 上就是一帧一帧的事件）。
 */
export type JsonRpcNotification = {
  jsonrpc: string;
  method: string;
  params?: unknown;
};
