// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorObject } from "./ErrorObject";
import type { RequestId } from "./RequestId";

export type JsonRpcError = {
  jsonrpc: string;
  /**
   * 解析不了 id 时（比如请求本身就是坏 JSON）为 null。
   */
  id: RequestId | null;
  error: ErrorObject;
};
