// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";

/**
 * 情景记忆的列表。**没有 cursor**：`Episodes::recent` 只按时间倒序取最近 N 条，
 * 存储层没有偏移量的概念。与其编一个用不了的游标，不如诚实地返回 null。
 */
export type MemoryListEpisodesResponse = {
  data: Array<Episode>;
  nextCursor: string | null;
};
