// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fact } from "./Fact";

export type MemoryRememberResponse = {
  /**
   * 写进去的完整 fact，带 id —— 前端可以直接插进列表，不用再查一次。
   */
  fact: Fact;
};
