// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryForgetResponse = {
  /**
   * 实际删掉多少条。0 表示本来就没有这个主题的记忆。
   */
  removed: number;
};
