// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Episode } from "./Episode";
import type { Fact } from "./Fact";

export type MemorySearchResponse = {
  facts: Array<Fact>;
  episodes: Array<Episode>;
};
