// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryRememberParams = {
  subject: string;
  content: string;
  /**
   * 不给就是 `user`（用户直接说的）。consolidation 从对话里提炼时传
   * `consolidation`，这样前端能区分「你告诉它的」和「它自己总结的」。
   */
  source?: string | null;
};
