// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageRole } from "./MessageRole";
import type { TurnMeta } from "./TurnMeta";

/**
 * 会话历史里的一条消息：`chat_log` 的一行。
 *
 * 跟实时那一路（`turnStarted` / `textDelta` / `turnCompleted`）说的是同一场
 * 对话的两个视角：实时那一路只为**这一次连接**活着（刷新即消失），
 * 这一条让「刷新、换台设备、换个时候再看」成为可能。
 */
export type Message = {
  /**
   * chat_log 的行号。**也是游标**：`session/messages` 的 cursor 就是它。
   * 用行号而不是时间戳：同一轮的两行是同一秒写进去的，时间戳分不出先后。
   */
  id: number;
  role: MessageRole;
  content: string;
  /**
   * ISO 8601（UTC）。写进来的时刻。
   */
  at: string;
  /**
   * 这一轮的遥测（检索门 / 工具 / 迭代 / 模型 / usage），**只有 assistant 行上有**。
   */
  meta: TurnMeta | null;
};
