// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 消息的角色。**闭集**，故意不留「未知」这个口子。
 *
 * `chat_log` 里将来若真多出别的角色，`session/messages` 会**跳过**那些行，
 * 而不是硬塞一个值进来 —— 前端那个 `switch` 才能是穷尽的，
 * 「还有第三种角色要画」这种事就会在编译期现形。
 */
export type MessageRole = "user" | "assistant";
