// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInfo } from "./ModelInfo";

export type ModelListResponse = {
  data: Array<ModelInfo>;
  nextCursor: string | null;
};
