// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInfo = {
  id: string;
  provider: string;
  label: string | null;
  flagship: string | null;
  fast: string | null;
};
