// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 请求 id：JSON-RPC 允许数字或字符串。
 *
 * 数字这一支是 `i32` 而不是 `u64`：`u64` 会被 ts-rs 映射成 TypeScript 的
 * `bigint`，而 `JSON.parse` 出来的是 `number` —— 客户端拿到 `1` 却被告知类型是
 * `bigint`，这是那种不报错、只在运行时对不上的 bug。跨语言边界只用 `i32`，
 * 跟 v2.rs 的规矩是同一条。
 */
export type RequestId = number | string;
