// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一次「正在重试」的说明。
 *
 * 重试**从不静默**：用户看到的是这句话，而不是一段莫名其妙的长时间停顿。
 */
export type RetryNotification = {
  turnId: string;
  /**
   * 第几次重试（从 1 开始）。
   */
  attempt: number;
  /**
   * 为什么重试（`HTTP 429` / `网络错误：…`）。
   */
  reason: string;
  /**
   * 等了多久。
   */
  delayMs: number;
};
