// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsolidationCompletedNotification } from "./ConsolidationCompletedNotification";
import type { ErrorNotification } from "./ErrorNotification";
import type { GateDecidedNotification } from "./GateDecidedNotification";
import type { GraphEndedNotification } from "./GraphEndedNotification";
import type { GraphNodeEndedNotification } from "./GraphNodeEndedNotification";
import type { GraphNodeStartedNotification } from "./GraphNodeStartedNotification";
import type { GraphStartedNotification } from "./GraphStartedNotification";
import type { RetryNotification } from "./RetryNotification";
import type { TextDeltaNotification } from "./TextDeltaNotification";
import type { ToolCompletedNotification } from "./ToolCompletedNotification";
import type { ToolStartedNotification } from "./ToolStartedNotification";
import type { TurnCompletedNotification } from "./TurnCompletedNotification";
import type { TurnStartedNotification } from "./TurnStartedNotification";

/**
 * 一轮 turn 的全部过程事件。
 *
 * `type` 是判别式 —— 前端拿它做 switch，Python 侧用 pydantic discriminated
 * union。**任何失败都不应让客户端崩**：这里只描述「发生了什么」。
 */
export type ServerNotification =
  | ({ type: "turnStarted" } & TurnStartedNotification)
  | ({ type: "textDelta" } & TextDeltaNotification)
  | ({ type: "gateDecided" } & GateDecidedNotification)
  | ({ type: "retry" } & RetryNotification)
  | ({ type: "toolStarted" } & ToolStartedNotification)
  | ({ type: "toolCompleted" } & ToolCompletedNotification)
  | ({ type: "consolidationCompleted" } & ConsolidationCompletedNotification)
  | ({ type: "graphStarted" } & GraphStartedNotification)
  | ({ type: "graphNodeStarted" } & GraphNodeStartedNotification)
  | ({ type: "graphNodeEnded" } & GraphNodeEndedNotification)
  | ({ type: "graphEnded" } & GraphEndedNotification)
  | ({ type: "turnCompleted" } & TurnCompletedNotification)
  | ({ type: "error" } & ErrorNotification);
