// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionNewParams = {
  /**
   * 不给就由服务端生成。
   */
  sessionId?: string | null;
};
