// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 读一个会话说过的话。
 *
 * **为什么需要它**：没有这个方法，页面上那场对话就只活在浏览器里 ——
 * 刷新一下全没了。它同时是「切换会话」的前提：切过去至少能看见那边说过什么。
 */
export type SessionMessagesParams = {
  sessionId: string;
  /**
   * 只取比这条消息**更早**的（往上翻旧账）。不给就是最新的那一页。
   */
  cursor?: string | null;
  limit?: number | null;
};
