// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * 消息**最新的在最前** —— 跟对话本身的方向相反，因为「往上翻」才是
 * 这个方法的用法：先拿最近一页，再顺着 `nextCursor` 往更早的地方走。
 */
export type SessionMessagesResponse = {
  data: Array<Message>;
  /**
   * 还有更早的才给：把它当下一次的 cursor。null = 到底了。
   */
  nextCursor: string | null;
};
