// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionSummary = {
  id: string;
  /**
   * 会话标题 = 第一条用户消息的前 60 个字。
   */
  title: string;
  messages: number;
  startedAt: string | null;
  lastAt: string | null;
};
