// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 配置的**写入补丁**。只传要改的字段，null 表示不改。
 */
export type SettingsPatch = {
  provider?: string | null;
  model?: string | null;
  smallModel?: string | null;
  maxIterations?: number | null;
  maxTokens?: number | null;
  historyTurns?: number | null;
  consolidateEvery?: number | null;
  retrievalTopK?: number | null;
  appleCalendar?: boolean | null;
  googleCalendar?: boolean | null;
  experimental?: boolean | null;
  graphWorkflows?: boolean | null;
  /**
   * 放行表（`JOY_EXEC_ALLOW`）的整表替换 —— 「记住这条命令」写的就是它。
   */
  execAllow?: Array<string> | null;
};
