// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 配置的**读取视图**。字段刻意全量且非可选：读出来就该是完整现状。
 */
export type SettingsView = {
  provider: string;
  model: string;
  smallModel: string;
  maxIterations: number;
  maxTokens: number;
  /**
   * 工作记忆滑窗：只把最近 N 轮塞进 prompt。
   */
  historyTurns: number;
  consolidateEvery: number;
  retrievalTopK: number;
  appleCalendar: boolean;
  googleCalendar: boolean;
  experimental: boolean;
  graphWorkflows: boolean;
  home: string;
};
