// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextDeltaNotification = {
  turnId: string;
  /**
   * 流式文本增量。只在 `turn/start` 传了 `stream: true` 时才有。
   */
  delta: string;
};
