// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type ToolCompletedNotification = {
  turnId: string;
  tool: string;
  /**
   * 工具回给模型看的文本。失败的详细信息也在这里 —— 不中断 turn。
   */
  output: string;
  status: ToolStatus;
  durationMs: number | null;
};
