// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

export type ToolCallRecord = {
  tool: string;
  status: ToolStatus;
  durationMs: number | null;
};
