// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolStartedNotification = {
  turnId: string;
  tool: string;
  /**
   * 模型给的参数，结构随工具而定。
   */
  args: unknown;
};
