// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";
import type { TurnMeta } from "./TurnMeta";

export type TurnCompletedNotification = {
  turnId: string;
  reply: string;
  iterations: number;
  meta: TurnMeta;
  usage: TokenUsage | null;
};
