// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GateDecision } from "./GateDecision";
import type { GraphInfo } from "./GraphInfo";
import type { TokenUsage } from "./TokenUsage";
import type { ToolCallRecord } from "./ToolCallRecord";

/**
 * 一轮 turn 的遥测。落库到 chat_log.meta，所以重开一个旧会话
 * 仍能看到当时是哪个脑子的哪个决定，而不只是最终那句回复。
 */
export type TurnMeta = {
  gate: GateDecision | null;
  /**
   * graph 没介入时为 null。
   */
  graph: GraphInfo | null;
  iterations: number;
  latencyMs: number;
  tools: Array<ToolCallRecord>;
  /**
   * 真正回答这一轮的模型：被 graph 判成 quick 时是小模型，如实记录。
   */
  model: string;
  provider: string;
  /**
   * 这一轮的 token 用量。只走过 `turnCompleted`、没进库的历史缺陷
   * 已经补上：现在它随 meta 一起落进 chat_log，重看历史也看得到花了多少。
   */
  usage: TokenUsage | null;
  /**
   * 这一轮被 `turn/interrupt` 打断时为 true。
   * 旧库里的 meta 没有这个字段 —— `#[serde(default)]` 让它们照常解析。
   */
  interrupted: boolean;
  /**
   * 循环护栏在这一轮命中几次（0 = 模型没有卡在重复/交替的工具调用里）。
   * 是 0 才正常；不为 0 说明这一轮的预算有一部分花在了原地打转上。
   */
  guardHits: number;
  /**
   * 命中时护栏对模型说的那句话（给人看的解释；没命中就是 null）。
   */
  guardNote: string | null;
};
