// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnStartParams = {
  sessionId?: string | null;
  message: string;
  /**
   * 是否逐 token 推送 `textDelta`。dashboard 开着，脚本调用关着。
   */
  stream?: boolean | null;
};
