// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TurnInterruptResponse = {
  /**
   * false = 这一轮已经跑完了，没打断到什么。
   */
  interrupted: boolean;
};
